### ISSUE TITLE
IMPORTANT - Maintainer / Code Owner Request

### ISSUE THREAD

**Issue by walsha2** [am15h/tflite_flutter_plugin#221]
# Background

Attempts at reaching @am15h have not worked. This repo is slowly getting very stale and breaking. It is 100% understandable if the original maintainers no longer have the time to support the plugin. Can we open the package to other maintainers? [tflite_flutter](https://pub.dev/packages/tflite_flutter) already has 300+ likes on pub.dev. It would be better to keep this package up to date rather than create clones with similar names and confuse users.

# Request

**Are there any repo members that are code owners or maintainers that have write access to the repo** so that this can continue to be maintained by the community? Otherwise, this repo can be considered dead and will end up with a series of copies flooding pub.dev. It is preferable to continue to maintain this repo instead - we just need someone with write access to allow for pull requests to be merged.

**Comment by JengaAttack** [comment]
Sorry can i ask, are there any good cloned maintained repos ATM?

**Comment by unayodev** [comment]
I agree walsha2, there are many packages that I can't use or have to use several older versions because the tflite_flutter package depends on the older versions. The same thing happens to me with the tflite_flutter_helper package

**Comment by PaulTR** [comment]
So I just got a message about this ticket and wanted to provide an update. The TensorFlow team has officially taken ownership of the pub.dev package and will be working to migrate this code over to the official TensorFlow GitHub org/repo. I'll try to remember to post here as soon as that's done, and I'll get a message up on the pub.dev page. It might take me like a month with IO and other stuff, but it's definitely in the works now!

**Comment by yaizudamashii** [comment]
Wow what an amazing news!  Long live TensorFlow and Flutter!

**Comment by walsha2** [comment]
@PaulTR that is fantastic news. Thank you for updating us and also appreciate you updating the pub.dev release with the following message. This should help warn users.

> The TensorFlow team has taken official ownership of this plugin and will begin migrating to the TensorFlow org with a team managed repo. You can follow the package on pub.dev for updates as we make progress. Our goal is to have this moved over by mid-May, then we'll start work on updates and accepting community contributions.

https://pub.dev/packages/tflite_flutter

When the time is appropriate, please mark the `tflite_flutter` package [as discontinued](https://dart.dev/tools/pub/publishing#discontinue) so that users no longer use this package.

**Comment by PaulTR** [comment]
We'll actually use the same package :) I'm just getting the repo under us rather than am15h. Will update and point it as 0.9.x when it's moved, then I think the next big goal is updating dependencies so it isn't restricting people trying to use it.

**Comment by charlieforward9** [comment]
@PaulTR amazing, thanks for updating us! Will we potentially see a merge with the [helper package](https://github.com/am15h/tflite_flutter_helper) as well?

**Comment by PaulTR** [comment]
> @PaulTR amazing, thanks for updating us! Will we potentially see a merge with the [helper package](https://github.com/am15h/tflite_flutter_helper) as well?

@charlieforward9 So from what I understand, the helper essentially worked like the [Task Library](https://www.tensorflow.org/lite/inference_with_metadata/task_library/overview), yeah? (sorry I haven't looked _that_ far into it yet). 

We have something called [MediaPipe](https://developers.google.com/mediapipe/solutions/examples) Tasks now that's basically an upgraded version of TFLite Tasks. Nothing is set in stone, but I'm sketching out a design doc that could be used for exposing all of that to Flutter and have enough buy-in that I'm confident in getting things moving forward (or as confident as we can be all things considered :P). I did get a quick "I wonder how I'd make this" app together for text classification that works, but that's the most simple use-case and I also need to learn how Flutter handles complex items over method channels - not a show stopper, I just know it's an area that I don't know :)

To give you a better idea, I wrote the samples for [Android here](https://github.com/googlesamples/mediapipe/tree/main/examples).

In particular I'd check out these classes for [text classification](https://github.com/googlesamples/mediapipe/blob/main/examples/text_classification/android/app/src/main/java/com/google/mediapipe/examples/textclassifier/TextClassifierHelper.kt), [gesture recognition](https://github.com/googlesamples/mediapipe/blob/main/examples/gesture_recognizer/android/app/src/main/java/com/google/mediapipe/examples/gesturerecognizer/GestureRecognizerHelper.kt), and [audio classification](https://github.com/googlesamples/mediapipe/blob/main/examples/audio_classifier/android/app/src/main/java/com/google/mediapipe/examples/audioclassifier/AudioClassifierHelper.kt). They're a little overly complex because the samples show live streaming data as well as uploading video/still images/audio files from the device, but the general idea is there.

**Comment by charlieforward9** [comment]
@PaulTR Thanks for all the details! I am still relatively new to the ML space but am working on a product that directly depends on this framework and some MediaPipe Solutions. 

With that said, I would like to hear how closely TensorFlow and MediaPipe are working together on a Flutter solution. I opened [this issue](https://github.com/google/mediapipe/issues/3922) a few months ago and haven't heard back, wondering if you have any insight on this?

**Comment by mdejeans** [comment]
> @PaulTR amazing, thanks for updating us! Will we potentially see a merge with the [helper package](https://github.com/am15h/tflite_flutter_helper) as well?

I've contributed on this package a long time ago. @PaulTR @walsha2  if you need any help maintening/merging/reviewing things, it will be with pleasure, just reach me out !

**Comment by PaulTR** [comment]
Hey @mdejeans I'll keep everyone posted. Right now I'm working through a ridiculous number of processes to get this moving forward internally :)

**Comment by PaulTR** [comment]
@charlieforward9 We're the same team :) I actually mostly work on MediaPipe, but trying to drive Flutter for TensorFlow since it already exists and just needs a little love.

**Comment by charlieforward9** [comment]
That's good to know. I agree with you! Thanks for putting in the work for us internally!

**Comment by JSYRD** [comment]
Amazing news! Finally got an official plugin for tflite! So should we contribute to this repo, or latter to the migrant repo?

**Comment by PaulTR** [comment]
Go ahead and contribute here. I'll review PRs before moving things over
once that's all prepared (still in process, but I have high hopes!) :) I'll
try to sit down this week to get the plugin working on my machine for
Android so I have a baseline for reviews.

**Comment by JSYRD** [comment]
Thank you! Now I've built the latest tflite binary and it worked successfully. Obviously the wiki needs updating, so do the releases, but maybe you can provide some official binaries as releases after migrant, rather than those built on our own. :) This plugin did help me a lot! I'll try to update the wiki.

**Comment by JSYRD** [comment]
> > ...but maybe you can provide some official binaries as releases after migrant, rather than those built on our own
> 
> @JSYRD do you know how to build the binaries? When I tried to build them, I only got the framework for ios, but I couldn't build the android binary. If you have fresh binaries, can you share them, please?

Yes I do, please check this: https://github.com/JSYRD/krccsnet/releases

**Comment by PaulTR** [comment]
Hey everyone! Time for the followup we've all been waiting for.

The repo has been officially moved over to the [TensorFlow org](https://github.com/tensorflow/flutter-tflite) in its current state. It's definitely going to take some time to update everything and get this to a runnable state, but I'm starting that long process now :) I'll first focus on all of the fun house-keeping things like repo management, copyright headers, and figuring out what documentation should be marked for updates. With some luck that'll be in a good place within a few weeks (though that could very likely fall behind as we approach I/O), then I'll start trying to get this building for mobile (Android + iOS). I want to say that I'll be able to get everything going for web+desktop not long after, but I honestly just don't know since those are a bit more out of my wheelhouse.

Similar to before, PRs are very much welcome in the new repo, especially during this ramp up time, so I'm definitely looking forward to the community applying their expertise as this moves forward.

Thanks all!

**Comment by mirland** [comment]
@PaulTR Thanks for the update. However, why did you create a new repo? In my opinion, you should [transfer the repo](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) (so the issues, history, and contributors are transferred), you shouldn't just copy it.

Also if you don't want to transfer it, you could just fork it, but as an OSS vision, you should not just drop the current state.
For example, a lot of years ago, Google took the work started by Square, and they [forked dagger](https://github.com/google/dagger) (and they make it much better) In that case Google was not the owner of Dagger, now you have the ownership here, that is why I think transferring is better than forking in this case.

That's just an opinion

**Comment by PaulTR** [comment]
@mirland Short answer is politics :) Internal systems with legal review for creating repos under our orgs and all that fun stuff.

**Comment by mirland** [comment]
Ok, in this case, I would add documentation in the readme telling that the new repo is hosted in the tf org(it's already done), then I'd close this issue and at the end, I'd archive this repository.

**Comment by PaulTR** [comment]
Closing the issue, but I don't actually have _admin_ rights on this repo. Can't archive it myself.
